MVCProjectCamp2/Controllers/UserSettingsController.cs
using BussinesLogicLayer.Concrete;
using BussinesLogicLayer.Validation;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntitiyLayer.Concrete;
using FluentValidation.Results;
using MVCProjectCamp2.Hash;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVCProjectCamp2.Controllers
{
    public class UserSettingsController : Controller
    {
        private readonly AdminManager mng = new AdminManager(new EFAdminDAL());
        private readonly AdminValidation validation = new AdminValidation();
        private readonly Context db = new Context();
        [Authorize(Roles = "B")]
        public ActionResult List()
        {
            ViewBag.update = TempData["update"];
            ViewBag.add = TempData["add"];
            List<Admin> deger = mng.GetList();
            return View(deger);
        }
        [HttpGet]
        [Authorize(Roles = "B")]
        public ActionResult Update(byte id)
        {
            Admin deger = mng.GetByID(id);
            return View(deger);
        }
        [HttpPost]
        [Authorize(Roles = "B")]
        public ActionResult Update(Admin p)
        {
            ValidationResult result = validation.Validate(p);
            if (result.IsValid)
            {
                Admin deger = mng.GetByID(p.ID);
                deger.PasswordAdmin = deger.PasswordAdmin == p.PasswordAdmin
                    ? p.PasswordAdmin
                    : Encryption.Enc(p.PasswordAdmin);
                deger.AdminRole = p.AdminRole;
                deger.UserNameAdmin = p.UserNameAdmin;
                deger.Mail = p.Mail;
                deger.Image = p.Image;
                mng.Update(deger);
                TempData["update"] = "update";
                return RedirectToAction("List");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        [Authorize(Roles = "B")]
        public PartialViewResult UserAdd()
        {
            return PartialView();
        }
        [Authorize(Roles = "B")]
        public ActionResult Add(Admin p)
        {
            ValidationResult result = validation.Validate(p);
            if (result.IsValid)
            {
                p.PasswordAdmin = Encryption.Enc(p.PasswordAdmin);
                p.Status = true;
                mng.Add(p);
                TempData["add"]="add";
                return RedirectToAction("List");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }
        [Authorize(Roles = "B")]
        public ActionResult StatusChanged(Admin p, byte id, bool status)
        {
            status = status ? status = false : status = true;
            var deger = db.Admins.FirstOrDefault(x => x.ID == id);
            deger.Status = status;
            mng.Update(deger);
            return RedirectToAction("List");
        }
    }
}

MVCProjectCamp2/Views/UserSettings/List.cshtml
@using MVCProjectCamp2.Hash
@model List<EntitiyLayer.Concrete.Admin>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    string btnclass = string.Empty, passivecontrol = string.Empty;
}
<h2 class="text-dark">ADMİN LİSTESİ</h2>
<hr />
<table id="tbl1" class="table table-hover">
    <thead>
        <tr>
            <th>#</th>
            <th>KULLANICI ADI</th>
            <th>ŞİFRESİ</th>
            <th>MAİL ADRESİ</th>
            <th>ROL</th>
            <th>RESİM</th>
            <th>GÜNCELLE</th>
            <th>DURUM</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <th>@item.ID</th>
                <td>@item.UserNameAdmin</td>
                <td>@Encryption.Desc(item.PasswordAdmin)</td>
                <td>@item.Mail</td>
                <td>
                    @item.AdminRole
                </td>
                <td><img width="50" height="50" src="@item.Image"></td>
                <td><a href="~/UserSettings/Update/@item.ID" class="btn btn-info">GÜNCELLE</a></td>
                @{
                    btnclass = @item.Status ? "btn btn-success" : "btn btn-danger";
                    passivecontrol = @item.Status ? "AKTİF" : "PASİF";
                }
                <td> @Html.ActionLink(@passivecontrol, "StatusChanged", "UserSettings", new { id = item.ID, status = item.Status }, new { @class = @btnclass, @onclick = "return confirm ('ADMİN DURUMU DEĞİŞTİRELECEKTİR EMİN MİSİNİZ ?')" })</td>
            </tr>
        }
    </tbody>
</table>
<br />
<button type="button" data-toggle="modal" data-target="#modal1" style="margin-left: 10px" class="btn btn-outline-warning">YENİ ADMİN EKLE</button>
<br />
<br />
<br />
<div class="form-control-feedback"><p style="color: red">* (B) EN YETKİLİ</p></div>
<div class="form-control-feedback"><p style="color: red">* (A) ORTA YETKİLİ</p></div>
<div class="form-control-feedback"><p style="color: red">* (C) EN YETKİSİZ</p></div>
@Html.Action("UserAdd", "UserSettings")
<script>
    $('#tbl1').DataTable(
        {
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.20/i18n/Turkish.json"
            }
        }
    );
</script>
@if (!string.IsNullOrEmpty(ViewBag.add) && ViewBag.add == "add")
{
    <script type="text/javascript">
        window.onload = function () {
            swal("Başarılı!", "Admin Ekleme İşlemi Başarılı", "success");
        };
    </script>
}
@if (!string.IsNullOrEmpty(ViewBag.update) && ViewBag.update == "update")
{
    <script type="text/javascript">
        window.onload = function () {
            swal("Başarılı!", "Admin Güncelleme  İşlemi Başarılı", "success");
        };
    </script>
}

MVCProjectCamp2/Views/UserSettings/Update.cshtml
@model EntitiyLayer.Concrete.Admin
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2 class="mt-0 text-dark">GÜNCELLEME SAYFASI</h2>
<hr />
@using (Html.BeginForm("Update", "UserSettings", FormMethod.Post))
{
    @Html.HiddenFor(x => x.ID, new { @class = "form-control", @readonly = true })
    @Html.HiddenFor(x=>x.Status)
    <br />
    <label>KULLANICI ADI</label>
    @Html.TextBoxFor(x => x.UserNameAdmin, new { @class = "form-control",placeholder = "Kullanıcı Adı Yazınız.." })
    @Html.ValidationMessageFor(x => x.UserNameAdmin, "", new { @class = "text-danger" })
    <br />
    <label>ŞİFRESİ</label>
    @Html.TextBoxFor(x =>x.PasswordAdmin, new { @type = "password", @class = "form-control", placeholder = "Şifrenizi Yazınız.." })
    @Html.ValidationMessageFor(x => x.PasswordAdmin, "", new { @class = "text-danger" })
    <br />
    <label>MAİL ADRESİNİZ</label>
    @Html.TextBoxFor(x =>x.Mail, new { @type = "email", @class = "form-control", @required = "", @maxlength = 75, placeholder = "Mail Adresi Yazınız.." })
    @Html.ValidationMessageFor(x => x.Mail, "", new { @class = "text-danger" })
    <br />
    <label>ROLE</label>
    <select class="form-control" id="AdminRole" name="AdminRole">
        <option>A</option> 
        <option>B</option> 
        <option>C</option> 
    </select>
    @Html.ValidationMessageFor(x => x.AdminRole, "", new { @class = "text-danger" })
    <br />
    <label>RESİM LİNKİ</label>
    @Html.TextBoxFor(x => x.Image, new {@class = "form-control", placeholder = "Resim Linki Yazınız.." })
    @Html.ValidationMessageFor(x => x.Image, "", new { @class = "text-danger" })
    <br /><br />
    <button class="btn btn-outline-success">ADMİN GÜNCELLE</button>
}
<br/>

MVCProjectCamp2/Views/UserSettings/UserAdd.cshtml
@model EntitiyLayer.Concrete.Admin
<div class="modal" id="modal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-title">
                    <a style="margin-left: 442px" href="~/UserSettings/List/" class="btn btn-outline-danger">X</a>
                    <h2 class="m-0 text-dark">KULLANICI EKLEME SAYFASI</h2><hr />
                    <div class="modal-body">
                        @using (Html.BeginForm("Add", "UserSettings", FormMethod.Post))
                        {
                            <label>KULLANICI ADI</label>
                            @Html.TextBoxFor(x => x.UserNameAdmin, new { @class = "form-control", @required = "", @maxlength = 50, placeholder = "Kullanıcı Adı Yazınız.." })
                            @Html.ValidationMessageFor(x => x.UserNameAdmin, "", new { @class = "text-danger" })
                            <br />
                            <label>ŞİFRESİ</label>
                            @Html.TextBoxFor(x => x.PasswordAdmin, new { @class = "form-control", @required = "", @maxlength = 50, @type ="password", placeholder = "****" })
                            @Html.ValidationMessageFor(x => x.PasswordAdmin, "", new { @class = "text-danger" })
                            <br />
                            <label>MAİL ADRESİNİZ</label>
                            @Html.TextBoxFor(x =>x.Mail, new { @type = "email", @class = "form-control", @required = "", @maxlength = 75, placeholder = "Mail Adresi Yazınız.." })
                            @Html.ValidationMessageFor(x => x.Mail, "", new { @class = "text-danger" })
                            <br />
                            <label>ROLÜ</label>
                            <select class="form-control" id="AdminRole" name="AdminRole">
                                <option>A</option> 
                                <option>B</option> 
                                <option>C</option> 
                            </select>
                            @Html.ValidationMessageFor(x => x.AdminRole, "", new { @class = "text-danger" })
                            <br />
                            <label>RESİM LİNKİ</label>
                            @Html.TextBoxFor(x => x.Image, new {@class = "form-control", placeholder = "Resim Linki Yazınız.." })
                            @Html.ValidationMessageFor(x => x.Image, "", new { @class = "text-danger" })
                            <br /><br />
                            <button type="submit" class="btn btn-outline-success">ADMİN EKLE</button>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>