MVCProjectCamp2/Controllers/AdminWriterController.cs
using System.Collections.Generic;
using BussinesLogicLayer.Concrete;
using BussinesLogicLayer.Validation;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntitiyLayer.Concrete;
using FluentValidation.Results;
using MVCProjectCamp2.Hash;
using PagedList;
using System.Linq;
using System.Web.Mvc;

namespace MVCProjectCamp2.Controllers
{
    [Authorize(Roles = "B")]
    public class AdminWriterController : Controller
    {
        private readonly WriterManager mng = new WriterManager(new EFWriterDAL());
        private readonly WriterValidation validation = new WriterValidation();
        private readonly Context db = new Context();
     
        public ActionResult WriterList(byte page = 1)
        {
            ViewBag.add = TempData["add"];
            ViewBag.update = TempData["update"];
            IPagedList<Writer> deger = mng.GetList().ToPagedList(page, 6);
            return View(deger);
        }
        [HttpGet]
        [Authorize]
        public ActionResult WriterAdd()
        {
            return View();
        }
        [Authorize]
        public ActionResult StatusChanged(Writer p, byte id, bool status)
        {
            status = status ? status = false : status = true;
            var deger = db.Writers.FirstOrDefault(x => x.WriterID == id);
            deger.Status = status;
            p = deger;
            db.Database.ExecuteSqlCommand("update Headings set Status='" + status + "' where WriterID=" + id + "");
            db.SaveChanges();
            db.Database.ExecuteSqlCommand("update Contents set Status='" + status + "' where WriterID=" + id + "");
            db.SaveChanges();
            return RedirectToAction("WriterList");
        }
        [HttpPost]
        [Authorize]
        public ActionResult WriterAdd(Writer p)
        {
            ValidationResult result = validation.Validate(p);
            if (result.IsValid)
            {
                p.Password = Encryption.Enc(p.Password);
                p.Status = true;
                mng.Add(p);
                TempData["add"] = "add";
                return RedirectToAction("WriterList");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View();
            }
        }
        [HttpGet]
        [Authorize]
        public ActionResult WriterUpdate(short id)
        {
            var deger = mng.GetById(id);
            return View(deger);
        }
        [HttpPost]
        [Authorize]
        public ActionResult WriterUpdate(Writer p)
        {
            ValidationResult result = validation.Validate(p);
            if (result.IsValid)
            {
                Writer deger = mng.GetById(p.WriterID);
                deger.Password = deger.Password == p.Password
                    ? p.Password
                    : Encryption.Enc(p.Password);
                deger.Contents = p.Contents;
                deger.WriterTitle = p.WriterTitle;
                deger.WriterSurName = p.WriterSurName;
                deger.WriterName = p.WriterName;
                deger.WriterAbout = p.WriterAbout;
                deger.Mail = p.Mail;
                deger.Image = p.Image;
                mng.Update(deger);
                TempData["update"] = "update";
                return RedirectToAction("WriterList");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View();
            }
        }

        public ActionResult GetByWriterHeading(short id)
        {
            List<Heading> deger=db.Headings.Where(x => x.WriterID == id).OrderByDescending(x => x.HeadingName).ToList();
            return View(deger);
        }
    }
}

MVCProjectCamp2/Views/AdminWriter/GetByWriterHeading.cshtml
@model List<EntitiyLayer.Concrete.Heading>
@{
    ViewBag.Title = "GetByWriterHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="row">
    <div class="col-md-12">
        <div class="timeline">
            @foreach (var item in Model)
            {<div>
                    <i class="fas fa-comments bg-yellow"></i>
                    <div class="timeline-item">
                        <span class="time"><i class="fas fa-clock"></i>@(((DateTime) item.Date).ToString("D"))</span>
                        <h3 class="timeline-header">   @item.Category.CategoryName KATEGORİSİ <a href="~/Home/GetBy/@item.HeadingID">@item.HeadingName</a> BAŞLIĞI    </h3>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<script src="~/AdminLTE-3.0.4/plugins/jquery/jquery.min.js"></script>
<script src="~/AdminLTE-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<script src="~/AdminLTE-3.0.4/dist/js/adminlte.min.js"></script>
<script src="~/AdminLTE-3.0.4/dist/js/demo.js"></script>

MVCProjectCamp2/Views/AdminWriter/WriterAdd.cshtml
@model EntitiyLayer.Concrete.Writer
@{
    ViewBag.Title = "WriterAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2 style="margin-left: 50px" class="m-0 text-dark">YENİ YAZAR EKLEME SAYFASI</h2>
<hr />
@using (Html.BeginForm("WriterAdd", "AdminWriter", FormMethod.Post))
{
    <label>YAZARIN ADI</label>
    @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control", @MaxLength = 30, @placeholder = "Yazarın Adı Giriniz.." })
    @Html.ValidationMessageFor(x => x.WriterName, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN SOYADI</label>
    @Html.TextBoxFor(x => x.WriterSurName, new { @class = "form-control", @MaxLength = 30, @placeholder = "Yazarın Soyadı Giriniz.." })
    @Html.ValidationMessageFor(x => x.WriterSurName, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN UNVANI</label>
    @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control", @MaxLength = 50, @placeholder = "Yazarın Unvanı Giriniz.." })
    @Html.ValidationMessageFor(x => x.WriterTitle, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN RESİM (LİNK)</label>
    @Html.TextBoxFor(x => x.Image, new { @class = "form-control", @MaxLength = 250, @placeholder = "Yazarın Resim Giriniz.." })
    @Html.ValidationMessageFor(x => x.Image, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN MAİLİ</label>
    @Html.TextBoxFor(x => x.Mail, new { @class = "form-control", @MaxLength = 50, @type = "email", @placeholder = "Yazarın Maili Giriniz.." })
    @Html.ValidationMessageFor(x => x.Mail, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN ŞİFRESİ</label>
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control", @MaxLength = 30, @type = "password", @placeholder = "Yazarın Şifresi Giriniz.." })
    @Html.ValidationMessageFor(x => x.Password, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN HAKKINDA BİLGİ</label>
    @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control", @MaxLength = 150, @style = "height: 100px", @placeholder = "Yazarın Hakkında Giriniz.." })
    @Html.ValidationMessageFor(x => x.WriterAbout, "", new { @class = "text-danger" })
    <br />
    <br />
    <button class="btn btn-outline-success" type="submit">YENİ YAZAR EKLE</button>
    <br />
    <br />
}

MVCProjectCamp2/Views/AdminWriter/WriterList.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<EntitiyLayer.Concrete.Writer>
@{
    ViewBag.Title = "WriterList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{
    string btnclass = string.Empty, passivecontrol = string.Empty;
}
<h2 style="margin-left:25px" class="m-0 text-dark">YAZAR LİSTESİ</h2>
<hr />
<section class="content">
    <div class="card card-solid">
        <div class="card-body pb-0">
            <div class="row d-flex align-items-stretch">
                @foreach (var item in Model)
                {
                    btnclass = @item.Status ? "btn btn-sm bg-teal" : "btn btn-sm bg-danger";
                    passivecontrol = @item.Status ? "AKTİF" : "PASİF";
                    <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                        <div class="card bg-light">
                            <div class="card-header text-muted border-bottom-0">
                                @item.WriterTitle
                            </div>
                            <div class="card-body pt-0">
                                <div class="row">
                                    <div class="col-7">
                                        <h2 class="lead"><b>@item.WriterName @item.WriterSurName</b></h2>
                                        <p class="text-muted text-sm"><b>Hakkında: </b> @item.WriterAbout.</p>
                                        <ul class="ml-4 mb-0 fa-ul text-muted">
                                            <li class="small"><span class="fa-li"><i class="fas fa-lg fa-sticky-note"></i></span><a href="mailto:@item.Mail">@item.Mail</a></li>
                                        </ul>
                                    </div>
                                    <div class="col-5 text-center">
                                        <img src="@item.Image" alt="" class="img-circle img-fluid">
                                    </div>
                                </div>
                            </div>
                            <div class="card-footer">
                                <div class="text-right">
                                    @Html.ActionLink(@passivecontrol, "StatusChanged", "AdminWriter", new { id = item.WriterID, status = item.Status }, new { @class = @btnclass, @onclick = "return confirm ('YAZARIN DURUMU DEĞİŞTİRELECEKTİR YAZARIN BAĞLI BAŞLIKLARINDA DURUMU DEĞİŞTİRELECEKTİR EMİN MİSİNİZ ?')" })
                                    <a href="~/AdminWriter/GetByWriterHeading/@item.WriterID" class="btn btn-sm bg-teal">
                                        <i class="fas fa-comments"> Yazarın Başlıkları</i>
                                    </a>
                                    <a href="~/AdminWriter/WriterUpdate/@item.WriterID" class="btn btn-sm btn-primary">
                                        <i class="fas fa-user"></i> Profili Düzenle
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <div style="margin-left: 20px"> @Html.PagedListPager((IPagedList)Model, page => Url.Action("WriterList", new { page }))</div>
        <div style="margin-left: 1400px"><a href="~/AdminWriter/WriterAdd/" class="btn btn-warning">YENİ YAZAR EKLE</a></div>
        <br />
    </div>
</section>
@if (!string.IsNullOrEmpty(ViewBag.add) && ViewBag.add == "add")
{
    <script type="text/javascript">
        window.onload = function () {
            swal("Başarılı!", "Yazar Ekleme İşlemi Başarılı", "success");
        };
    </script>
}
@if (!string.IsNullOrEmpty(ViewBag.update) && ViewBag.update == "update")
{
<script type="text/javascript">
    window.onload = function () {
        swal("Başarılı!", "Yazar Güncelleme  İşlemi Başarılı", "success");
    };
</script>
}

MVCProjectCamp2/Views/AdminWriter/WriterUpdate.cshtml
@model EntitiyLayer.Concrete.Writer
@{
    ViewBag.Title = "WriterUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<h2 style="margin-left: 50px" class="m-0 text-dark">YAZAR GÜNCELLEME SAYFASI</h2>
<hr />
@using (Html.BeginForm("WriterUpdate", "AdminWriter", FormMethod.Post))
{
    @Html.HiddenFor(x => x.WriterID)
    @Html.HiddenFor(x=>x.Status)
    <label>YAZARIN ADI</label>
    @Html.TextBoxFor(x => x.WriterName, new { @class = "form-control", @MaxLength = 30, @placeholder = "Yazarın Adı Giriniz.." })
    @Html.ValidationMessageFor(x => x.WriterName, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN SOYADI</label>
    @Html.TextBoxFor(x => x.WriterSurName, new { @class = "form-control", @MaxLength = 30, @placeholder = "Yazarın Soyadı Giriniz.." })
    @Html.ValidationMessageFor(x => x.WriterSurName, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN UNVANI</label>
    @Html.TextBoxFor(x => x.WriterTitle, new { @class = "form-control", @MaxLength = 50, @placeholder = "Yazarın Unvanı Giriniz.." })
    @Html.ValidationMessageFor(x => x.WriterTitle, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN RESİM (LİNK)</label>
    @Html.TextBoxFor(x => x.Image, new { @class = "form-control", @MaxLength = 250, @placeholder = "Yazarın Resim Giriniz.." })
    @Html.ValidationMessageFor(x => x.Image, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN MAİLİ</label>
    @Html.TextBoxFor(x => x.Mail, new { @class = "form-control", @MaxLength = 50, @type = "email", @placeholder = "Yazarın Maili Giriniz.." })
    @Html.ValidationMessageFor(x => x.Mail, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN ŞİFRESİ</label>
    @Html.TextBoxFor(x => x.Password, new { @class = "form-control", @MaxLength = 30, @type = "password", @placeholder = "Yazarın Şifresi Giriniz.." })
    @Html.ValidationMessageFor(x => x.Password, "", new { @class = "text-danger" })
    <br />
    <label>YAZARIN HAKKINDA BİLGİ</label>
    @Html.TextAreaFor(x => x.WriterAbout, new { @class = "form-control", @MaxLength = 150, @style = "height: 100px", @placeholder = "Yazarın Hakkında Giriniz.." })
    @Html.ValidationMessageFor(x => x.WriterAbout, "", new { @class = "text-danger" })
    <br />
    <br />
    <button class="btn btn-outline-success" type="submit">YAZAR GÜNCELLE</button>
    <br />
    <br />
}