MVCProjectCamp2/Controllers/WriterWriteController.cs
using BussinesLogicLayer.Concrete;
using BussinesLogicLayer.Validation;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntitiyLayer.Concrete;
using FluentValidation.Results;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVCProjectCamp2.Controllers
{
    public class WriterWriteController : Controller
    {
        private readonly ContentManager db = new ContentManager(new EFContentDAL());
        private readonly HeadingManager ct = new HeadingManager(new EFHeadingDAL());
        private readonly ContentValidation validation = new ContentValidation();
        private readonly Context mng = new Context();
        public ActionResult List(byte page = 1)
        {
            ViewBag.message = TempData["message"] as string;
            string mail = (string)Session["WriterMail"];
            Writer user = mng.Writers.FirstOrDefault(x => x.Mail == mail);
            var deger = db.WhereList(x => x.WriterID == user.WriterID).ToPagedList(page, 6);
            ViewBag.dgr = deger.Select(x => x.Heading.HeadingName).FirstOrDefault();
            return View(deger);
        }
        public ActionResult StatusChanged(Content p, byte id, bool status)
        {
            status = status ? status = false : status = true;
            var deger = mng.Contents.FirstOrDefault(x => x.ContentID == id);
            deger.Status = status;
            p = deger;
            mng.SaveChanges();
            return RedirectToAction("List");
        }
        [HttpGet]
        [ValidateInput(false)]
        public ActionResult Update(short id)
        {
            Content deger = mng.Contents.FirstOrDefault(x => x.ContentID == id);
            return View(deger);
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Update(Content p)
        {
            ValidationResult result = validation.Validate(p);
            if (result.IsValid)
            {
                db.Update(p);
                TempData["message"] = "update";
                return RedirectToAction("List");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View("List");
            }
        }

        public ActionResult AllList()
        {
            ViewBag.message = TempData["message"] as string;
            List<Heading> deger = ct.WhereList(x => x.Status == true).ToList();
            return View(deger);
        }
        [HttpGet]
        public ActionResult HeadingContent(short id)
        {
            TempData["headingid"] = id;
            Heading deger = ct.GetById(id);
            ViewBag.dgr = deger.HeadingName.ToString();
            return View();
        }
        [HttpPost]
        [ValidateInput(false)]
        public ActionResult HeadingContent(Content p)
        {
            p.HeadingID = (short)TempData["headingid"];
            p.Date = DateTime.Now;
            string user = (string)Session["WriterMail"];
            Writer mail = mng.Writers.FirstOrDefault(x => x.Mail == user);
            p.WriterID = mail.WriterID;
            p.Status = true;
            ValidationResult result = validation.Validate(p);
            if (result.IsValid)
            {
                db.Add(p);
                TempData["message"] = "add";
                return RedirectToAction("AllList");
            }
            else
            {
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
                return View();
            }
        }
    }
}

MVCProjectCamp2/Views/WriterWrite/AllList.cshtml
@model List<EntitiyLayer.Concrete.Heading>
@{
    ViewBag.Title = "AllList";
    Layout = "~/Views/Shared/Writer_Layout.cshtml";
    short idhead = 0;
}
<h2 class="m-0 text-dark">TÜM BAŞLIKLAR LİSTESİ</h2>
<hr />
<div class="card">
    <div class="card-header">
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                <i class="fas fa-times"></i>
            </button>
        </div>
    </div>
    <div class="card-body p-0">
        <table id="tbl1" class="table table-striped projects">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th class="text-center" style="width: 20%">
                        BAŞLIĞIN ADI
                    </th>
                    <th class="text-center" style="width: 20%">
                        OLUŞTURAN YAZAR
                    </th>
                    <th class="text-center">
                        KATEGORİSİ
                    </th>
                    <th style="width: 20%">
                        İŞLEMLER
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.HeadingID
                        </td>
                        <td class="text-center">
                            <a>
                                @item.HeadingName
                            </a>
                            <br />
                            <small>
                                @(((DateTime)item.Date).ToString("yyyy MMMM dd"))
                            </small>
                        </td>
                        <td class="text-center">
                            <img alt="Avatar" height="50" class="table-avatar" src="@item.Writer.Image">
                            <br />
                            @item.Writer.WriterName @item.Writer.WriterSurName
                        </td>
                        <td class="text-center">
                            @item.Category.CategoryName
                        </td>
                        <td class="project-actions text-right">
                            <a class="btn btn-primary btn-sm" href="~/Home/GetBy/@item.HeadingID">
                                <i class="fas fa-folder">
                                </i>
                                Yazılar
                            </a>
                            <a class="btn btn-info btn-sm" href="~/WriterWrite/HeadingContent/@item.HeadingID">
                                <i class="fas fa-pencil-alt">
                                </i>
                                Yorum Yap
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    $('#tbl1').DataTable(
        {
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.20/i18n/Turkish.json"
            }
        }
    );
</script>
@if (!string.IsNullOrEmpty(ViewBag.message) && ViewBag.message == "add")
{
    <script type="text/javascript">
        window.onload = function () {
            swal("Başarılı!", "Başlığa Yorum Ekleme İşlemi Başarılı", "success");
        };
    </script>
}

MVCProjectCamp2/Views/WriterWrite/HeadingContent.cshtml
@model EntitiyLayer.Concrete.Content
@{
    ViewBag.Title = "HeadingContent";
    Layout = "~/Views/Shared/Writer_Layout.cshtml";
}
<h2 class="text-dark">@ViewBag.dgr Başlığına Yorum Yap</h2>
<hr/>
@using (Html.BeginForm("HeadingContent", "WriterWrite", FormMethod.Post))
{
    <label>YORUM ALANI</label>
    @Html.TextAreaFor(x => x.ContentText, new { @class = "form-control",required="", @style = "height: 300px", @id = "compose-textarea" })
@Html.ValidationMessageFor(x => x.ContentText, "", new { @class = "text-danger" })
<br />
<button type="submit" class="btn btn-outline-success">YENİ YORUM EKLE</button>
}

MVCProjectCamp2/Views/WriterWrite/List.cshtml
@using PagedList.Mvc
@using PagedList
@model PagedList.IPagedList<EntitiyLayer.Concrete.Content>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/Writer_Layout.cshtml";
}
@{
    string btnclass = string.Empty, passivecontrol = string.Empty;
}
<h2 class="text-dark">Başlıklara Yaptığım Yorumlar</h2>
<hr />
<br />
@foreach (var item in Model)
{
    <h3 style="color: darkblue;margin-left:30px">@item.Heading.HeadingName</h3>
    <div class="col-md-9">
        <div class="card">
            <div class="card-body">
                <div class="tab-content">
                    <div class="active tab-pane" id="activity">
                        <div class="post">
                            <div class="user-block">
                                <img class="img-circle img-bordered-sm" src="@item.Writer.Image" alt="user image">
                                <span class="username">
                                    <a href="~/Home/GetBy/@item.HeadingID">@item.Writer.WriterName @item.Writer.WriterSurName</a>
                                </span>
                                <span class="description">@(((DateTime) item.Date).ToString("D"))</span>
                            </div>
                            <p>
                                @Html.Raw(item.ContentText)
                            </p>
                        </div>
                    </div>
                    <a href="~/WriterWrite/Update/@item.ContentID" class="btn btn-outline-secondary">Yorumu Düzenle</a>
                    @{
                        btnclass = @item.Status ? "btn btn-success" : "btn btn-danger";
                        passivecontrol = @item.Status ? "AKTİF" : "PASİF";
                    }
                    @Html.ActionLink(@passivecontrol, "StatusChanged", "WriterWrite", new { id = item.ContentID, status = item.Status }, new { @class = @btnclass, @onclick = "return confirm ('YORUMUNUZUN DURUMU DEĞİŞTİRELECEKTİR EMİN MİSİNİZ ?')" })
                </div>
            </div>
        </div>
    </div>
    <hr />
}
<div> @Html.PagedListPager((IPagedList)Model, page => Url.Action("List", new { page }))</div>
@if (!string.IsNullOrEmpty(ViewBag.message) && ViewBag.message == "update")
{
    <script type="text/javascript">
        window.onload = function () {
            swal("Başarılı!", "Başlığın Yorumu Güncelleme İşlemi Başarılı", "success");
        };
    </script>
}

MVCProjectCamp2/Views/WriterWrite/Update.cshtml
@model EntitiyLayer.Concrete.Content
@{
    ViewBag.Title = "Update";
    Layout = "~/Views/Shared/Writer_Layout.cshtml";
}
<h1 class="mt-0 text-dark">YORUMU GÜNCELLE</h1>
<hr />
@using (Html.BeginForm("Update", "WriterWrite", FormMethod.Post))
{@Html.HiddenFor(x => x.ContentID)
@Html.HiddenFor(x => x.HeadingID)
@Html.HiddenFor(x => x.WriterID)
@Html.HiddenFor(x => x.Status)
@Html.HiddenFor(x => x.Date)
<label>YORUMUNUZ</label>
@Html.TextAreaFor(x => x.ContentText, new { @class = "form-control", required = "", @style = "height: 300px", @id = "compose-textarea" })
@Html.ValidationMessageFor(x => x.ContentText, "", new { @class = "text-danger" })
<br />
<button type="submit" class="btn btn-outline-success">YORUMU GÜNCELLE</button>
}