MVCProjectCamp2/Controllers/AdminContactController.cs
using BussinesLogicLayer.Concrete;
using BussinesLogicLayer.Validation;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntitiyFramework;
using EntitiyLayer.Concrete;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MVCProjectCamp2.Controllers
{
    public class AdminContactController : Controller
    {
        private readonly ContactManager db = new ContactManager(new EFContactDAL());
        private readonly MessageManager mng = new MessageManager(new EFMessageDAL());
        private readonly Context ct = new Context();
        private readonly ContactValidation Validation = new ContactValidation();
        [Authorize]
        public ActionResult List()
        {
            ViewBag.concat = TempData["concat"] as string;
            List<Contact> deger = db.List().OrderByDescending(x => x.ContactID).ToList();
            return View(deger);
        }
        [Authorize]
        public ActionResult GetList(short id)
        {
            ct.Database.ExecuteSqlCommand("update Contacts set [Read]=1 where ContactID=" + id + "");
            ct.SaveChanges();
            Contact deger = db.GetByID(id);
            return View(deger);
        }
        [Authorize]
        public PartialViewResult SideBar()
        {
            string user = (string)Session["UserNameAdmin"];
            Admin mail = ct.Admins.FirstOrDefault(x => x.UserNameAdmin == user);
            ViewBag.msg = db.List().Count.ToString();
            ViewBag.send = mng.WhereList(x => x.Sender == mail.Mail && x.Status == true).Count.ToString();
            ViewBag.inbox = mng.WhereList(x => x.Receiver == mail.Mail && x.Status == true).Count.ToString();
            ViewBag.delete = mng.WhereList(x => x.Receiver == mail.Mail ^ x.Sender == mail.Mail && x.Status == false).Count.ToString();
            return PartialView();
        }
        [Authorize]
        public ActionResult Delete(short id)
        {
            Contact deger = db.GetByID(id);
            db.Delete(deger);
            TempData["concat"] = "concat";
            return RedirectToAction("List");
        }
    }
}

MVCProjectCamp2/Views/AdminContact/GetList.cshtml
@model EntitiyLayer.Concrete.Contact
@{
    ViewBag.Title = "GetList";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<section class="content">
    <div class="row">
        @Html.Action("SideBar","AdminContact")
    <div class="col-md-9">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h3 class="card-title">İletişim Detay</h3>
                </div>
                <div class="card-body p-0">
                    <div class="mailbox-read-info">
                        <h5>@Model.Subject</h5>
                        <h6>
                            Kimden: <a href="mailto:@Model.Mail">@Model.Mail</a>
                            <span class="mailbox-read-time float-right">@(((DateTime)Model.Date).ToString("f"))</span>
                        </h6>
                    </div>
                    <div class="mailbox-read-message">
                       <b><p>@Model.UserName</p></b>
                        <p>
                       @Model.ContentText
                        </p>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="~/AdminContact/Delete/@Model.ContactID" class="btn btn-default"><i class="far fa-trash-alt"></i> Sil</a>
                </div>
            </div>
    </div>
    </div>
</section>

MVCProjectCamp2/Views/AdminContact/List.cshtml
@model List<EntitiyLayer.Concrete.Contact>
@{
    ViewBag.Title = "List";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<section class="content">
    <div class="row">
        @Html.Action("SideBar", "AdminContact")
        <div class="col-md-9">
            <div class="card card-primary card-outline">
                <div class="card-header">
                    <h3 class="card-title">İletişim Kutusu</h3>
                </div>
                <div class="card-body p-0">
                    <div class="table-responsive mailbox-messages">
                        <table id="tbl1" class="table table-hover table-striped">
                            <thead>
                                <tr>
                                    <th>Mesaj Yollayan</th>
                                    <th>Konusu</th>
                                    <th>Tarih</th>
                                    <th>Durum</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td class="mailbox-name"><a href="~/AdminContact/GetList/@item.ContactID">@item.UserName</a></td>
                                        <td class="mailbox-subject">
                                            <b>@item.Subject</b>
                                        </td>

                                        <td class="mailbox-date">@(((DateTime) item.Date).ToString("f"))</td>
                                        @{
                                            string read = item.Read != false ? "OKUNDU" : "OKUNMADI";
                                            string suc = read == "OKUNDU" ? "badge bg-success float-right" : "badge bg-danger float-right";
                                        }
                                        <td><span class="@suc">@read</span></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
<script>
    $('#tbl1').DataTable(
        {
            "language": {
                "url": "https://cdn.datatables.net/plug-ins/1.10.20/i18n/Turkish.json"
            }
        }
    );
</script>
@if (!string.IsNullOrEmpty(ViewBag.concat) && ViewBag.concat == "concat")
{
    <script type="text/javascript">
        window.onload = function () {
            swal("Başarılı!", "İletişim Silme İşlemi Başarılı", "success");
        };
    </script>
}

MVCProjectCamp2/Views/AdminContact/SideBar.cshtml
<div class="col-md-3">
    <div class="card">
        <a href="~/Message/AddMessage/" class="btn btn-primary btn-block mb-3">Yeni Mesaj Oluştur</a>
        <div class="card-header">
            <h3 class="card-title">Seçenekler</h3>
            <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                    <i class="fas fa-minus"></i>
                </button>
            </div>
        </div>
        <div class="card-body p-0">
            <ul class="nav nav-pills flex-column">
                <li class="nav-item active">
                    <a href="~/Message/List" class="nav-link">
                        <i class="fas fa-inbox"></i> Gelen Mesajlar
                        <span class="badge bg-primary float-right">@ViewBag.inbox</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="~/Message/SendMail" class="nav-link">
                        <i class="far fa-envelope"></i> Gönderilen Mesajlar
                        <span class="badge bg-primary float-right">@ViewBag.send</span>
                    </a>
                </li>
                <li class="nav-item active">
                    <a href="~/AdminContact/List" class="nav-link">
                        <i class="fas fa-mail-bulk"></i> İletişim
                        <span class="badge bg-primary float-right">@ViewBag.msg</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="~/Message/DeleteList" class="nav-link">
                        <i class="far fa-trash-alt"></i> Çöp Kutusu
                        <span class="badge bg-danger float-right">@ViewBag.delete</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>